# current machine's name, optional; it can be used to filter settings or in the commit message
hostname: "sunvo-MacBookPro"
# more details at https://github.com/zokugun/vscode-sync-settings/blob/master/docs/hostname.md

# selected profile, required
profile: main


# sync on remote git
repository:
  type: git
  # url of the remote git repository to sync with, required
  url: git@github.com:FerretAngel/vscode-setting-sync.git
  # branch to sync on, optional (set to `master` by default)
  branch: main
